name: CI/CD

on:
  push:
    branches:
      - master
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Run Tests
        run: bun run test:coverage

      - name: Build Project
        run: bun run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: bin/

  publish:
    name: Publish to npm
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Build Project
        run: bun run build

      - name: Publish Package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
